apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "registry-rewriter.fullname" . }}
  labels:
    app: {{ template "registry-rewriter.name" . }}
    chart: {{ template "registry-rewriter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
webhooks:
- clientConfig:
    service:
      namespace: kube-system
      name: {{ template "registry-rewriter.fullname" . }}-service
    caBundle: {{ .Values.caBundle }}
  failurePolicy: Fail
  name: {{ template "registry-rewriter.fullname" . }}-service.kube-system.svc
  namespaceSelector:
    matchExpressions:
      - key: mutateimagename
        operator: NotIn
        values: [never]
  rules:
  - apiGroups:
    - apps
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - deployments

