apiVersion: v1
kind: Service
metadata:
  name: {{ template "registry-rewriter.fullname" . }}-service
  namespace: kube-system
  labels:
    app: {{ template "registry-rewriter.name" . }}
    chart: {{ template "registry-rewriter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 443
    targetPort: https
  selector:
    app: {{ template "registry-rewriter.name" . }}
    release: {{ .Release.Name }}