language: generic
sudo: required
services:
- docker

before_script:
  - make docker
  - make docker-test


deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

env:
  global:
  - DOCKER_FOLDER=lawrencegripper