apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-repository-controller-deployment
  labels:
    app: local-repository-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: local-repository-controller
  template:
    metadata:
      labels:
        app: local-repository-controller
    spec:
      containers:
      - name: controller
        image: lawrencegripper/local-repository
        ports:
        - containerPort: 443
          name: https
---
apiVersion: v1
kind: Service
metadata:
  name: local-repository-controller-service
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: https
  selector:
    app: local-repository-controller
  type: LoadBalancer
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: local-repository-controller-webhook
webhooks:
- clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU0akNDQXNxZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFSTVE4d0RRWURWUVFERXdaeWIyOTAKWTJFd0hoY05NVGd3T0RFME1UVXhOREF4V2hjTk1qQXdNakUwTVRVeE5EQXhXakFSTVE4d0RRWURWUVFERXdaeQpiMjkwWTJFd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUURJL2NCa3U3a21SR090Cm0rcEZNZVd5MUh5UG0zSFBZUzZ6ekJBNGt0c1JkejZ6WGFyOWVJVDFudUt1bC9melF6NHRRSUlNZE5hRmZHaWsKSUVjSU5odlo2RHJIcWtEU2xIa3YzT0Vwc2ZIYkdCcGZyaDM4NHBPREZ2YWpmcWx5QnZ3WGFRZ2xiUWZaU0dxYgpVN3FRa1VFSFRIQ2xUMkcxcVFsbk8xUXNpUTQ5dkcraU9CdzJpM0RsS1IzRk5DVGd1eEZtejBVZmxlczdpOGtMCmpKbW1pNTNFdzlVVGVrcVhxSXZ1QVNoaEEzSzhWckRISk9ZYWR5M3VBU1dSaWlGMDJOQkFvdHdZcjBhUEtwZFMKdmZSQzN0TFNuTENGZU90Q1ZZS2doYi8vZ1huZFlUUUpxdDJEalEzY1kxaUt0UU1vZjhEK1ZFOWhpdGhGREtXego2V0k2VCt0UjBtSUNlNDJxUGZjd1VCaEZTTVhuN0NCZEFpVmNmK1Z6RWRKOWd6aFJqN1BNYitjcXlXOTdSYURuCm01alNKYzJYWFpFQnJack1Wb3BBOFZZSTY5cmNuZm9GTERrS08wTStEMVRONGd3UkhTamNaSDN6dE1NZEI0VVcKQzVxRHFMSEVnWmJ2UHBnd1p5WloyUlNtRlI3OTJ6Yitpbzg3ejI0NjVOTFVqQ2NiVWk2V0JSa203UllWUi9jYQpnd0loNUtHYzlnRFZodmRMZlRlU1JSdnMySUN6RWZ0UVlXZlBvM3J4NWs3QUoxWkdzUVY0N2RTRFBYZ0Z5MEgzCnBZaXQrTmJXYXVSa3JNcEh1SjVGWkg1TUtjV1ludVNBVDlBdmJHcFpHRUdUbDhkak5Jb0tySytsL3JsSXZIdFcKVDZhNC94dVl4V0N6WUFBZlNLYjJFNUNWRnlHWHBRSURBUUFCbzBVd1F6QU9CZ05WSFE4QkFmOEVCQU1DQVFZdwpFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBREFkQmdOVkhRNEVGZ1FVYWdFZ3dmelR0TWpHZjZSY2k0Yjl3Z1FqCmJIVXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnSUJBRlZ3KzdVVEpSSkltQzRMR01tdUN1ODhQY0dXNFJnZXJJeFYKWk10eWlEVTV2ckMxS2xWdVh0Q0YwcGYrMVpkaWlYemdwQVZMSE1ZakVwbDlTMDJyT2xpcXdGU29hZkMvTEptWgpOdndHZTUxeGpOR1N5VFdKalpBMnJ0Y3kzcndMNytPVnc2Q20zRGVqejlBSHN6aFg5RWtaajllRHdCSS9hK1ZqCmdDSmZTZXNoeEYxWW41cXp4NHBEWmlVNXk5NzEzRENaQXpFTTZBTUJrMTBIbzlheHV2WVA1ZmVtaVpXanNoS0wKV2MyMnhlNlhveXczUzltM2lwdGRnUjRwQ2xlemlNMElkM293U3d2Nng3RVNzRXFxM2x5TXVoUTRiZkFkN1lQMAppbXZXTWVIUnZlVmhBWjg3TmdTZmp4alV2Wlh0eFU5NFcvd1VWTmJOUWVQWitNRW5YaXNDdEpjZVNKRDZOVlA5CnRCdTdWYTFEcUpVVFRIS25oK3lIRVhTcTduWTZSWFNJYnhTeFhxMmdxVHlleGRHZHEvY1VlQkFKVzBkWEs5UGoKSXhyZU1EeVdaQ0JtOTQ0UkY5d3RhTHNLZUdXcW5mZTY5ZmR0U2FiQkxXaWxLb09SS0MxQWh4R0NCa0QrbEpZbgpUc1M5VXN2MHh2b3VUMmdRWFF0bmgvdTFDb2xkZVlqTk5QcTZVbkRSR0ZrY0tQZmZEdVltVG9qSmRTa2UwUTMzCnpnU01hb0xCRHpqUDRYNi9XK1ZRY1NVSmJkaThUOGJJU05IcTh4SmZ0MmI5SVNjZ25mQ0xNZHJqYys2TmxlZWgKNkNtejg5NE9LUW5yNzBZcHNVbEx4emJFcEl6aFBxWk5oWmhmVEpKOFRNSC9QYnFSTTgvNndac25IK21XcmIzRQpCRTF0bWR5VQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service: 
      name: local-repository-controller-service
      namespace: default
  failurePolicy: Fail
  name: local-repository-controller-service.default.svc.cluster.local
  namespaceSelector: {}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
